"""Critic node for evaluating Ad Creatives in the LangGraph pipeline."""

import json
import logging

from app.config import settings
from app.core.llm import get_router
from app.state import BlitzState

logger = logging.getLogger(__name__)

# Sourced from ADS_SYNTHESIS_PROMPT's own generation instructions ("Max 30
# chars for Google, 40 for Meta/LinkedIn"), not invented for this check.
_HEADLINE_CHAR_LIMITS = {"Google Ads": 30, "Meta Ads": 40, "LinkedIn Ads": 40}
_MAX_WORDS = 50

CRITIC_PROMPT = """
You are an expert marketing director evaluating ad creatives generated by your team.
Here are the generated ads in JSON format:
{ads_json}

Length and character limits have already been checked mechanically - do not judge those.
Your job is the part that needs a human eye: is the copy specific and punchy, or generic corporate jargon?
Are the visuals highly specific, or could they be any company in the category?

If the ads meet these criteria, respond with EXACTLY:
{{"approved": true, "feedback": "Great job."}}

If the ads are generic or use corporate jargon, respond with:
{{"approved": false, "feedback": "<specific reasons why they failed and what to change>"}}

Respond ONLY with valid JSON matching the schema above.
"""


def _length_violations(ads_output: dict) -> list[str]:
    """Word and character limits, checked in Python instead of asked of a model.

    A model judged a 12-word ad body as exceeding a 50-word limit once - a
    fact that doesn't need judgment, just counting. Word count covers
    headline + body + cta together: "the ad copy... under 50 words" means
    the whole ad, not one field in isolation.
    """
    violations: list[str] = []

    def _check(item: dict, label: str) -> None:
        headline = item.get("headline", "")
        body = item.get("body", "")
        cta = item.get("cta", "")
        word_count = len(f"{headline} {body} {cta}".split())
        if word_count > _MAX_WORDS:
            violations.append(f"{label}: {word_count} words, limit is {_MAX_WORDS}")

        limit = _HEADLINE_CHAR_LIMITS.get(item.get("platform"))
        if limit and len(headline) > limit:
            violations.append(
                f"{label}: headline is {len(headline)} chars, {item.get('platform')} limit is {limit}"
            )

    for ad in ads_output.get("ad_copies") or []:
        _check(ad, f"{ad.get('segment', '?')} / {ad.get('platform', '?')}")
    for ab in ads_output.get("ab_variations") or []:
        _check(ab, f"{ab.get('ad_copy_ref', '?')} / {ab.get('variant_label', '?')}")

    return violations


async def critic_ads_node(state: BlitzState) -> dict:
    """Evaluates the ad creative output and determines if it requires a rewrite.

    Caps revisions at 2 to prevent infinite loops.
    """
    revision_count = state.get("ads_revision_count") or 0

    if revision_count >= 2:
        logger.info("Ads critic: Max revisions reached, forcing approval.")
        return {
            "ads_approved": True,
            "ads_critic_feedback": None,
            "ads_revision_count": revision_count + 1
        }

    ads_output = state.get("ads_output", {})

    length_violations = _length_violations(ads_output)
    if length_violations:
        return {
            "ads_approved": False,
            "ads_critic_feedback": "; ".join(length_violations),
            "ads_revision_count": revision_count + 1
        }

    ads_json = json.dumps(ads_output)
    prompt = CRITIC_PROMPT.format(ads_json=ads_json)

    try:
        response = await get_router().acompletion(
            model="primary",
            messages=[{"role": "user", "content": prompt}],
            temperature=settings.critic_temperature,
            response_format={"type": "json_object"},
        )

        content = response.choices[0].message.content or "{}"
        data = json.loads(content)
        approved = data.get("approved", False)
        feedback = data.get("feedback", "")
    except Exception as e:
        logger.warning(f"Ads critic parse failed: {e}. Defaulting to approval.")
        approved = True
        feedback = ""

    return {
        "ads_approved": approved,
        "ads_critic_feedback": feedback if not approved else None,
        "ads_revision_count": revision_count + 1
    }
