"""Critic node for evaluating Ad Creatives in the LangGraph pipeline."""

import json
import logging


from app.config import settings
from app.core.llm import get_router
from app.state import BlitzState

logger = logging.getLogger(__name__)

CRITIC_PROMPT = """
You are an expert marketing director evaluating ad creatives generated by your team.
Here are the generated ads in JSON format:
{ads_json}

Your goal is to ensure the ad copy is concise, punchy, and under 50 words per variant, and that the visuals are highly specific.
Do not accept generic corporate jargon or long paragraphs.

If the ads meet these criteria, respond with EXACTLY:
{{"approved": true, "feedback": "Great job."}}

If the ads are too long, generic, or use corporate jargon, respond with:
{{"approved": false, "feedback": "<specific reasons why they failed and what to change>"}}

Respond ONLY with valid JSON matching the schema above.
"""

async def critic_ads_node(state: BlitzState) -> dict:
    """Evaluates the ad creative output and determines if it requires a rewrite.
    
    Caps revisions at 2 to prevent infinite loops.
    """
    revision_count = state.get("ads_revision_count") or 0
    
    if revision_count >= 2:
        logger.info("Ads critic: Max revisions reached, forcing approval.")
        return {
            "ads_approved": True,
            "ads_critic_feedback": None,
            "ads_revision_count": revision_count + 1
        }
        
    ads_output = state.get("ads_output", {})
    ads_json = json.dumps(ads_output)
    
    prompt = CRITIC_PROMPT.format(ads_json=ads_json)
    
    try:
        response = await get_router().acompletion(
            model="primary",
            messages=[{"role": "user", "content": prompt}],
            temperature=settings.critic_temperature,
            response_format={"type": "json_object"},
        )
        
        content = response.choices[0].message.content or "{}"
        data = json.loads(content)
        approved = data.get("approved", False)
        feedback = data.get("feedback", "")
    except Exception as e:
        logger.warning(f"Ads critic parse failed: {e}. Defaulting to approval.")
        approved = True
        feedback = ""

    return {
        "ads_approved": approved,
        "ads_critic_feedback": feedback if not approved else None,
        "ads_revision_count": revision_count + 1
    }
